[package]
name = "rsc"
version = "0.1.0"
edition = "2021"
authors = ["Gyorgy Jerovetz <jerovetz@comlions.net>"]
description = "A Solr client for Rust."

[dependencies]
reqwest = "0.11.16"
serde_json = "1.0.95"

[package.metadata.scripts]
start-solr = "docker run -d --rm -v solrdata:/var/solr -p 8983:8983 solr:8"
